name: My First Github Action Atique

on:
 push:
  branches:
    - main
 pull_request:
   branches:
     - main  
jobs:
 build: 
  runs-on: ubuntu-latest
  steps:
   - name: Welcome All
     run: echo "CI Pipeline running for PPTR."
   - name: Show DATE
     run: date

   - name: Show Linux Version
     run: uname -aaa
     
 test:
   runs-on: ubuntu-24.04
   steps:
   - name: Run Tests
     run: echo " Tests are running."

   - name: Show DATE
     run: date

   - name: Show Linux info
     run: uname -a
     
   
