name: My First Github Action Atique

on: push

jobs:
 job1: 
  runs-on: ubuntu-latest
  step:
   - name: Welcome All
     run: echo "Heloo Muhamamd, Job1 is running."
  
   - name: Show DATE
     run: date

   - name: Show Linux Version
     run: uname -a
     
 job2:
  runs-on: ubuntu-24.04
  steps:
   - name: Second Job Not Welcome All
     run: echo " job 2 is running."

   - name: Show DATE
     run: date

   - name: Show Linux Version
     run: uname -a
     
   
